
package vista;

import control.Control_Proveedores;
import javax.swing.JOptionPane;



public class IU_AgregarProveedor extends javax.swing.JInternalFrame {

<<<<<<< HEAD
   Control_Proveedores conectar;
   String sql;
=======
    
   
    
    /**
     * Creates new form FrmAgregarProveedor
     */
>>>>>>> DSCamilo
    public IU_AgregarProveedor() {
        initComponents();
        conectar=new Control_Proveedores();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregarproveedor_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombreempresa = new javax.swing.JTextField();
        txttelefonoempresa = new javax.swing.JTextField();
        txtcorreoempresa = new javax.swing.JTextField();
        btn_agregarproveedor_1 = new javax.swing.JButton();

        setTitle("Agregar proveedor");

        btn_agregarproveedor_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_agregarproveedor_.setText("Agregar proveedor");
        btn_agregarproveedor_.setToolTipText("Registrar Usuario");
        btn_agregarproveedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarproveedor_ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Agregar proveedor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre empresa:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/agregarproveedor 64.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefono");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Correo electronico");

<<<<<<< HEAD
        btn_agregarproveedor_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_agregarproveedor_1.setText("Cancelar");
        btn_agregarproveedor_1.setToolTipText("Registrar Usuario");
        btn_agregarproveedor_1.addActionListener(new java.awt.event.ActionListener() {
=======
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/cancel32.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> DSCamilo
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarproveedor_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(btn_agregarproveedor_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregarproveedor_1))
=======
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_agregarproveedor_))
>>>>>>> DSCamilo
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcorreoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombreempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefonoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombreempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttelefonoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcorreoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarproveedor_)
                    .addComponent(btn_agregarproveedor_1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarproveedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarproveedor_ActionPerformed
       if (txtnombreempresa.getText().isEmpty()|| txttelefonoempresa.getText().isEmpty()||txtcorreoempresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"No se puede continuar. Hay celdas vacias" );
        }else{
       
        if (txttelefonoempresa.getText().matches("[0-9]*")) {
              conectar.conectar();
       int telefono=Integer.parseInt(txttelefonoempresa.getText());
       
       sql="insert into proveedores (nombre_e,telefono,correo)values('"+txtnombreempresa.getText()+"','"+telefono+"','"+txtcorreoempresa.getText()+"')";
       conectar.agregarproveedor(sql);
                                   
        //JOptionPane.showMessageDialog(null, "Registro exitoso");
        }else{
            JOptionPane.showMessageDialog(null, "Solo se puede ingresar valores de tipo numerico ");
        }
        
      }
    }//GEN-LAST:event_btn_agregarproveedor_ActionPerformed

<<<<<<< HEAD
    private void btn_agregarproveedor_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarproveedor_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarproveedor_1ActionPerformed
=======
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
      //  dispose();
     
     
     
    }//GEN-LAST:event_jButton1ActionPerformed
>>>>>>> DSCamilo

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      dispose();
      IU_Proveedores restaurarVentanas = new IU_Proveedores();
      
      restaurarVentanas.isVisible();
    }//GEN-LAST:event_jButton1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarproveedor_;
    private javax.swing.JButton btn_agregarproveedor_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcorreoempresa;
    private javax.swing.JTextField txtnombreempresa;
    private javax.swing.JTextField txttelefonoempresa;
    // End of variables declaration//GEN-END:variables
}
