package vista;

import java.awt.Dimension;
import java.util.Locale;
import javax.swing.JFrame;

public class IU_Proveedores extends javax.swing.JInternalFrame {

    public Dimension dim;

    /**
     * Creates new form IU_Productos
     */
    public IU_Proveedores() {
        initComponents();

        dim = super.getToolkit().getScreenSize();
        super.setSize(dim);
//        super.setUndecorated(true);
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desk_ModuloProveedores = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        AgregarProveedor_ = new javax.swing.JMenu();
        BuscarProveedor_ = new javax.swing.JMenu();

        setClosable(true);
        setTitle("Modulo Proveedores");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout Desk_ModuloProveedoresLayout = new javax.swing.GroupLayout(Desk_ModuloProveedores);
        Desk_ModuloProveedores.setLayout(Desk_ModuloProveedoresLayout);
        Desk_ModuloProveedoresLayout.setHorizontalGroup(
            Desk_ModuloProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        Desk_ModuloProveedoresLayout.setVerticalGroup(
            Desk_ModuloProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        getContentPane().add(Desk_ModuloProveedores);

        AgregarProveedor_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/registrar produc_mov prod.png"))); // NOI18N
        AgregarProveedor_.setText("Agregar proveedor");
        AgregarProveedor_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarProveedor_MouseClicked(evt);
            }
        });
        AgregarProveedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProveedor_ActionPerformed(evt);
            }
        });
        jMenuBar1.add(AgregarProveedor_);

        BuscarProveedor_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/buscar produc mod pro.png"))); // NOI18N
        BuscarProveedor_.setText("Consultar proveedor");
        BuscarProveedor_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProveedor_MouseClicked(evt);
            }
        });
        jMenuBar1.add(BuscarProveedor_);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProveedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProveedor_ActionPerformed

    }//GEN-LAST:event_AgregarProveedor_ActionPerformed

    private void AgregarProveedor_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarProveedor_MouseClicked

        //   Desk_ModuloProveedores.removeAll();
        //  Desk_ModuloProveedores.revalidate();
        IU_AgregarProveedor IUAgregarProveedor = new IU_AgregarProveedor();
        Desk_ModuloProveedores.add(IUAgregarProveedor);
        IUAgregarProveedor.show();


    }//GEN-LAST:event_AgregarProveedor_MouseClicked

    private void BuscarProveedor_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProveedor_MouseClicked
//       Desk_ModuloProveedores.removeAll();
        //     Desk_ModuloProveedores.revalidate();
        IU_ConsultarProveedor IU_ConsultarProveedor = new IU_ConsultarProveedor();
        Desk_ModuloProveedores.add(IU_ConsultarProveedor);
        IU_ConsultarProveedor.show();


    }//GEN-LAST:event_BuscarProveedor_MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgregarProveedor_;
    private javax.swing.JMenu BuscarProveedor_;
    private javax.swing.JDesktopPane Desk_ModuloProveedores;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
