/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Control_Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class IU_RegistrarUsuario extends javax.swing.JInternalFrame {

   Control_Usuario conectar;
   String sql;
    public IU_RegistrarUsuario() {
     
        initComponents();
         setTitle("Registrar Usuario");
        conectar=new Control_Usuario();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusuarioregistro = new javax.swing.JTextField();
        txtcontraseñaregistro = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btn_RegistrarUsuario_ = new javax.swing.JButton();
        btn_CancelarRegistroUsuario_ = new javax.swing.JButton();
        tipousuario = new javax.swing.JRadioButton();

        setTitle("Registrar Usuario");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registro nuevo usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");

        txtcontraseñaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaregistroActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/registrar usuario 64.png"))); // NOI18N

        btn_RegistrarUsuario_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_RegistrarUsuario_.setText("Registrar");
        btn_RegistrarUsuario_.setToolTipText("Registrar Usuario");
        btn_RegistrarUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuario_ActionPerformed(evt);
            }
        });

        btn_CancelarRegistroUsuario_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_CancelarRegistroUsuario_.setText("Cancelar");
        btn_CancelarRegistroUsuario_.setToolTipText("Canclar Registro");
        btn_CancelarRegistroUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarRegistroUsuario_ActionPerformed(evt);
            }
        });

        tipousuario.setText("Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btn_RegistrarUsuario_))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_CancelarRegistroUsuario_)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtusuarioregistro)
                                .addComponent(txtcontraseñaregistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tipousuario))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtusuarioregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontraseñaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_RegistrarUsuario_))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_CancelarRegistroUsuario_)))
                .addGap(17, 17, 17)
                .addComponent(tipousuario)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuario_ActionPerformed
         String pass=String.valueOf(txtcontraseñaregistro.getPassword()); 
        if (pass.isEmpty()|| txtusuarioregistro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"No se puede continuar. Hay celdas vacias" );
        }else{
               conectar.conectar();
        String tipo="Vendedor";
        if ( tipousuario.isSelected()) {
            tipo="Administrador";
        }
       
       
        sql="insert into usuarios (usuario,password,tipo)values('"+txtusuarioregistro.getText()+"','"+pass+"','"+tipo+"')";
        conectar.registrarusuario(sql);
        }

     
    }//GEN-LAST:event_btn_RegistrarUsuario_ActionPerformed

    private void btn_CancelarRegistroUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarRegistroUsuario_ActionPerformed
    dispose();
    }//GEN-LAST:event_btn_CancelarRegistroUsuario_ActionPerformed

    private void txtcontraseñaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaregistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelarRegistroUsuario_;
    private javax.swing.JButton btn_RegistrarUsuario_;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton tipousuario;
    private javax.swing.JPasswordField txtcontraseñaregistro;
    private javax.swing.JTextField txtusuarioregistro;
    // End of variables declaration//GEN-END:variables
}
