
package vista;

import control.Control_Usuario;
import javax.swing.JOptionPane;


public class IU_Usuario extends javax.swing.JInternalFrame {

   Control_Usuario conectar;
   String sql;
    public IU_Usuario() {
     
        initComponents();
       
        conectar=new Control_Usuario();
        
        Grupobotones.add(tipoadmin);
        Grupobotones.add(tipovendedor);
        Grupobotones.setSelected(tipovendedor.getModel(), true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupobotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusuarioregistro = new javax.swing.JTextField();
        txtcontraseñaregistro = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btn_RegistrarUsuario_ = new javax.swing.JButton();
        tipoadmin = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tipovendedor = new javax.swing.JRadioButton();

        setBorder(null);
        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuarios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");

        txtcontraseñaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaregistroActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/registrar usuario 64.png"))); // NOI18N

        btn_RegistrarUsuario_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_RegistrarUsuario_.setText("Registrar");
        btn_RegistrarUsuario_.setToolTipText("Registrar Usuario");
        btn_RegistrarUsuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuario_ActionPerformed(evt);
            }
        });

        tipoadmin.setText("Administrador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo");

        tipovendedor.setText("Vendedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtusuarioregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcontraseñaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipoadmin)
                                .addComponent(tipovendedor)))
                        .addComponent(btn_RegistrarUsuario_, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuarioregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontraseñaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoadmin)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipovendedor)
                .addGap(11, 11, 11)
                .addComponent(btn_RegistrarUsuario_)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarUsuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuario_ActionPerformed
         String pass=String.valueOf(txtcontraseñaregistro.getPassword()); 
        if (pass.isEmpty()|| txtusuarioregistro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"No se puede continuar. Hay celdas vacias" );
        }else{
               conectar.conectar();
        String tipo="Vendedor";
        if ( tipoadmin.isSelected()) {
            tipo="Administrador";
        }
       
       
        sql="insert into usuarios (usuario,password,tipo)values('"+txtusuarioregistro.getText()+"','"+pass+"','"+tipo+"')";
        conectar.registrarusuario(sql);
        }

     
    }//GEN-LAST:event_btn_RegistrarUsuario_ActionPerformed

    private void txtcontraseñaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaregistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup Grupobotones;
    javax.swing.JButton btn_RegistrarUsuario_;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel6;
    javax.swing.JPanel jPanel1;
    javax.swing.JRadioButton tipoadmin;
    javax.swing.JRadioButton tipovendedor;
    javax.swing.JPasswordField txtcontraseñaregistro;
    javax.swing.JTextField txtusuarioregistro;
    // End of variables declaration//GEN-END:variables
}
